import { defaultPrompt } from './prompt.js';
import { defaultTemplates } from './templates.js';

export const defaultPresets = {
	endpoint: 'http://127.0.0.1:8080',
	endpointAPI: 0,
	endpointAPIKey: '',
	endpointModel: '',
	prompt: [{ type: 'user', content: defaultPrompt }],
	seed: -1,
	maxPredictTokens: -1,
	temperature: 0.7,
	dynaTempRange: 0,
	dynaTempExp: 1,
	repeatPenalty: 1.1,
	repeatLastN: 256,
	penalizeNl: false,
	presencePenalty: 0,
	frequencyPenalty: 0,
	topK: 40,
	topP: 0.95,
	typicalP: 1,
	minP: 0,
	tfsZ: 1,
	mirostat: 0,
	mirostatTau: 5.0,
	mirostatEta: 0.1,
	xtcThreshold: 0.1,
	xtcProbability: 0,
	dryMultiplier: 0,
	dryBase: 1.75,
	dryAllowedLength: 2,
	dryPenaltyRange: 1024,
	drySequenceBreakers: "[\"\\n\", \":\", \"\\\"\", \"*\"]",
	bannedTokens: "[]",
	stoppingStrings: "[]",
	useBasicStoppingMode: true,
	basicStoppingModeType: 'max_tokens',
	ignoreEos: false,
	openaiPresets: false,
	contextLength: 8192,
	tokenRatio: 3.3,
	memoryTokens: ({ "contextOrder":"{memPrefix}{wiPrefix}{wiText}{wiSuffix}{memText}{memSuffix}{prompt}","prefix":"", "text":"", "suffix":""}),
	authorNoteTokens: ({ "prefix":"", "text":"", "suffix":""}),
	authorNoteDepth: 3,
	worldInfo:({
		"mikuPediaVersion": 1,
		"entries": [],
		"prefix": "",
		"suffix": ""
	}),
	logitBias:{ bias:{},model:"none" },
	instructTemplates: defaultTemplates,
	scrollTop: 0,
	enabledSamplers: ['temperature', 'rep_pen', 'pres_pen', 'freq_pen', 'mirostat', 'top_k', 'top_p', 'min_p'],
	grammar: '',
	useServerTokenization: false,
	tokenizerModel: null,
	chatAPI: false,
	tokenStreaming: true,
	disableLogprobs: false,
	promptPreview: false,
	promptPreviewTokens: 20,
};
