import type { Dispatch, RefObject, SetStateAction } from 'react';

interface PromptChunk {
  type?: 'user';
  content: string;
  prob?: number;
  completion_probabilities?: CompletionProb[];
  top_logprobs?: any;
}

interface SettingsState {
  sessionStorage: SessionStorage;
  templateStorage: TemplateStorage;
  themeStorage: ThemeStorage;
  connectionStorage: ConnectionStorage;
  useSessionState: <T>(name: string, initialState: T) => [T, Dispatch<SetStateAction<T>>];
  useDBTemplates: <T>(initialState: T) => [Record<string, InstructTemplate>, Dispatch<SetStateAction<Record<string, InstructTemplate>>>];
  useDBThemes: <T>(initialState: T) => [Record<string, ThemeData>, Dispatch<SetStateAction<Record<string, ThemeData>>>];
  useDBConnections: <T>(initialState: T) => [Record<string, ConnectionData>, Dispatch<SetStateAction<Record<string, ConnectionData>>>];
  isMiyapadEndpoint: boolean;
  connections: Record<string, ConnectionData>;
  setConnections: Dispatch<SetStateAction<Record<string, ConnectionData>>>;
  selectedConnectionId: string;
  setSelectedConnectionId: Dispatch<SetStateAction<string>>;
  templates: Record<string, InstructTemplate>;
  setTemplates: Dispatch<SetStateAction<Record<string, InstructTemplate>>>;
  templateReplacements: boolean;
  setTemplateReplacements: Dispatch<SetStateAction<boolean>>;
  templatesImport: boolean;
  setTemplatesImport: Dispatch<SetStateAction<boolean>>;
  selectedTemplate: string;
  setSelectedTemplate: Dispatch<SetStateAction<string>>;
  templateList: TemplateListItem[];
  setTemplateList: Dispatch<SetStateAction<TemplateListItem[]>>;
  chatMode: boolean;
  setChatMode: Dispatch<SetStateAction<boolean>>;
  fontSizeMultiplier: number;
  setFontSizeMultiplier: Dispatch<SetStateAction<number>>;
  spellCheck: boolean;
  setSpellCheck: Dispatch<SetStateAction<boolean>>;
  attachSidebar: boolean;
  setAttachSidebar: Dispatch<SetStateAction<boolean>>;
  showProbsMode: number;
  setShowProbsMode: Dispatch<SetStateAction<number>>;
  editorFont: string;
  setEditorFont: Dispatch<SetStateAction<string>>;
  uiFont: string;
  setUIFont: Dispatch<SetStateAction<string>>;
  tokenHighlightMode: number;
  setTokenHighlightMode: Dispatch<SetStateAction<number>>;
  tokenColorMode: number;
  setTokenColorMode: Dispatch<SetStateAction<number>>;
  preserveCursorPosition: boolean;
  setPreserveCursorPosition: Dispatch<SetStateAction<boolean>>;
  promptAreaWidth: string | undefined;
  setPromptAreaWidth: Dispatch<SetStateAction<string | undefined>>;
  showAPIKey: boolean;
  setShowAPIKey: Dispatch<SetStateAction<boolean>>;
  endpoint: string;
  setEndpoint: Dispatch<SetStateAction<string>>;
  endpointAPI: number;
  setEndpointAPI: Dispatch<SetStateAction<number>>;
  endpointAPIKey: string;
  setEndpointAPIKey: Dispatch<SetStateAction<string>>;
  endpointModel: string;
  setEndpointModel: Dispatch<SetStateAction<string>>;
  seed: number;
  setSeed: Dispatch<SetStateAction<number>>;
  maxPredictTokens: number;
  setMaxPredictTokens: Dispatch<SetStateAction<number>>;
  temperature: number;
  setTemperature: Dispatch<SetStateAction<number>>;
  dynaTempRange: number;
  setDynaTempRange: Dispatch<SetStateAction<number>>;
  dynaTempExp: number;
  setDynaTempExp: Dispatch<SetStateAction<number>>;
  repeatPenalty: number;
  setRepeatPenalty: Dispatch<SetStateAction<number>>;
  repeatLastN: number;
  setRepeatLastN: Dispatch<SetStateAction<number>>;
  penalizeNl: boolean;
  setPenalizeNl: Dispatch<SetStateAction<boolean>>;
  presencePenalty: number;
  setPresencePenalty: Dispatch<SetStateAction<number>>;
  frequencyPenalty: number;
  setFrequencyPenalty: Dispatch<SetStateAction<number>>;
  topK: number;
  setTopK: Dispatch<SetStateAction<number>>;
  topP: number;
  setTopP: Dispatch<SetStateAction<number>>;
  typicalP: number;
  setTypicalP: Dispatch<SetStateAction<number>>;
  minP: number;
  setMinP: Dispatch<SetStateAction<number>>;
  tfsZ: number;
  setTfsZ: Dispatch<SetStateAction<number>>;
  mirostat: number;
  setMirostat: Dispatch<SetStateAction<number>>;
  mirostatTau: number;
  setMirostatTau: Dispatch<SetStateAction<number>>;
  mirostatEta: number;
  setMirostatEta: Dispatch<SetStateAction<number>>;
  xtcThreshold: number;
  setXtcThreshold: Dispatch<SetStateAction<number>>;
  xtcProbability: number;
  setXtcProbability: Dispatch<SetStateAction<number>>;
  dryMultiplier: number;
  setDryMultiplier: Dispatch<SetStateAction<number>>;
  dryBase: number;
  setDryBase: Dispatch<SetStateAction<number>>;
  dryAllowedLength: number;
  setDryAllowedLength: Dispatch<SetStateAction<number>>;
  dryPenaltyRange: number;
  setDryPenaltyRange: Dispatch<SetStateAction<number>>;
  drySequenceBreakers: string;
  setDrySequenceBreakers: Dispatch<SetStateAction<string>>;
  drySequenceBreakersError: string | undefined;
  setDrySequenceBreakersError: Dispatch<SetStateAction<string | undefined>>;
  bannedTokens: string;
  setBannedTokens: Dispatch<SetStateAction<string>>;
  bannedTokensError: string | undefined;
  setBannedTokensError: Dispatch<SetStateAction<string | undefined>>;
  ignoreEos: boolean;
  setIgnoreEos: Dispatch<SetStateAction<boolean>>;
  openaiPresets: boolean;
  setOpenaiPresets: Dispatch<SetStateAction<boolean>>;
  stoppingStrings: string;
  setStoppingStrings: Dispatch<SetStateAction<string>>;
  stoppingStringsError: string | undefined;
  setStoppingStringsError: Dispatch<SetStateAction<string | undefined>>;
  useBasicStoppingMode: boolean;
  setUseBasicStoppingMode: Dispatch<SetStateAction<boolean>>;
  basicStoppingModeType: string;
  setBasicStoppingModeType: Dispatch<SetStateAction<string>>;
  logitBias: LogitBiasState;
  setLogitBias: Dispatch<SetStateAction<LogitBiasState>>;
  logitBiasParam: Record<string, any>;
  setLogitBiasParam: Dispatch<SetStateAction<Record<string, any>>>;
  contextLength: number;
  setContextLength: Dispatch<SetStateAction<number>>;
  memoryTokens: MemoryTokensData;
  setMemoryTokens: Dispatch<SetStateAction<MemoryTokensData>>;
  authorNoteTokens: AuthorNoteData;
  setAuthorNoteTokens: Dispatch<SetStateAction<AuthorNoteData>>;
  authorNoteDepth: number;
  setAuthorNoteDepth: Dispatch<SetStateAction<number>>;
  worldInfo: WorldInfoData;
  setWorldInfo: Dispatch<SetStateAction<WorldInfoData>>;
  sillyTarvernWorldInfoJSON: any;
  setSillyTarvernWorldInfoJSON: Dispatch<SetStateAction<any>>;
  enabledSamplers: string[];
  setEnabledSamplers: Dispatch<SetStateAction<string[]>>;
  grammar: string;
  setGrammar: Dispatch<SetStateAction<string>>;
  useChatAPI: boolean;
  setUseChatAPI: Dispatch<SetStateAction<boolean>>;
  useTokenStreaming: boolean;
  setUseTokenStreaming: Dispatch<SetStateAction<boolean>>;
  disableLogprobs: boolean;
  setDisableLogprobs: Dispatch<SetStateAction<boolean>>;
  postSamplingProbs: boolean;
  setPostSamplingProbs: Dispatch<SetStateAction<boolean>>;
  showPromptPreview: boolean;
  setShowPromptPreview: Dispatch<SetStateAction<boolean>>;
  promptPreviewTokens: number;
  setPromptPreviewTokens: Dispatch<SetStateAction<number>>;
  currentThemeName: string;
  setCurrentThemeName: Dispatch<SetStateAction<string>>;
  allThemes: Record<string, ThemeData>;
  setAllThemes: Dispatch<SetStateAction<Record<string, ThemeData>>>;
  showMarkdownPreview: boolean;
  setShowMarkdownPreview: Dispatch<SetStateAction<boolean>>;
  ttsEnabled: boolean;
  setTTSEnabled: Dispatch<SetStateAction<boolean>>;
  ttsVoiceId: number;
  setTTSVoiceId: Dispatch<SetStateAction<number>>;
  ttsPitch: number;
  setTTSPitch: Dispatch<SetStateAction<number>>;
  ttsRate: number;
  setTTSRate: Dispatch<SetStateAction<number>>;
  ttsVolume: number;
  setTTSVolume: Dispatch<SetStateAction<number>>;
  ttsSpeakInputs: boolean;
  setTTSSpeakInputs: Dispatch<SetStateAction<boolean>>;
  ttsMaxUserInput: number;
  setTTSMaxUserInput: Dispatch<SetStateAction<number>>;
  useServerTokenization: boolean;
  setUseServerTokenization: Dispatch<SetStateAction<boolean>>;
  tokenizerModel: string | null;
  setTokenizerModel: Dispatch<SetStateAction<string | null>>;
  screenshotIncludeSessionName: boolean;
  setScreenshotIncludeSessionName: Dispatch<SetStateAction<boolean>>;
  screenshotIncludeDate: boolean;
  setScreenshotIncludeDate: Dispatch<SetStateAction<boolean>>;
  screenshotBackgroundUrl: string;
  setScreenshotBackgroundUrl: Dispatch<SetStateAction<string>>;
  screenshotBackgroundColor: string;
  setScreenshotBackgroundColor: Dispatch<SetStateAction<string>>;
  screenshotStoryFont: string;
  setScreenshotStoryFont: Dispatch<SetStateAction<string>>;
  screenshotGeneralFont: string;
  setScreenshotGeneralFont: Dispatch<SetStateAction<string>>;
  screenshotFontWeight: string;
  setScreenshotFontWeight: Dispatch<SetStateAction<string>>;
  screenshotFontSize: number;
  setScreenshotFontSize: Dispatch<SetStateAction<number>>;
  screenshotLineHeight: number;
  setScreenshotLineHeight: Dispatch<SetStateAction<number>>;
  screenshotFontColor: string;
  setScreenshotFontColor: Dispatch<SetStateAction<string>>;
  screenshotAiTextColor: string;
  setScreenshotAiTextColor: Dispatch<SetStateAction<string>>;
  screenshotModelAvatarUrl: string;
  setScreenshotModelAvatarUrl: Dispatch<SetStateAction<string>>;
}

export interface GenerationState {
  promptArea: RefObject<HTMLTextAreaElement | null>;
  promptOverlay: RefObject<HTMLDivElement | null>;
  undoStack: RefObject<number[]>;
  redoStack: RefObject<any[][]>;
  probsDelayTimer: RefObject<any>;
  keyState: RefObject<any>;
  sessionReconnectTimer: RefObject<number | undefined>;
  useScrollSmoothing: RefObject<boolean>;
  hordeTaskId: RefObject<string | undefined>;
  promptPreviewElement: RefObject<HTMLSpanElement | null>;
  markdownPreviewRef: RefObject<HTMLDivElement | null>;
  isSyncingScroll: RefObject<boolean>;
  ttsNewText: RefObject<string>;
  ttsLastChunk: RefObject<string>;
  ttsQueue: RefObject<string[]>;
  ttsVoices: RefObject<SpeechSynthesisVoice[]>;
  ttsPaused: RefObject<boolean>;
  activeGenId: RefObject<number>;
  abortControllerRef: RefObject<AbortController | null>;
  promptChunks: PromptChunk[];
  setPromptChunks: Dispatch<SetStateAction<PromptChunk[]>>;
  currentPromptChunk: { index: number; top: number; left: number } | undefined;
  setCurrentPromptChunk: Dispatch<{ index: number; top: number; left: number } | undefined>;
  undoHovered: boolean;
  setUndoHovered: Dispatch<SetStateAction<boolean>>;
  showProbs: boolean;
  setShowProbs: Dispatch<SetStateAction<boolean>>;
  cancel: (() => void) | null;
  setCancel: Dispatch<SetStateAction<(() => void) | null>>;
  sessionEndpointConnecting: boolean;
  setSessionEndpointConnecting: Dispatch<SetStateAction<boolean>>;
  sessionEndpointError: string | undefined;
  setSessionEndpointError: Dispatch<SetStateAction<string | undefined>>;
  rejectedAPIKey: boolean;
  setRejectedAPIKey: Dispatch<SetStateAction<boolean>>;
  openaiModels: any[];
  setOpenaiModels: Dispatch<SetStateAction<any[]>>;
  tokens: number;
  setTokens: Dispatch<SetStateAction<number>>;
  tokensPerSec: number;
  setTokensPerSec: Dispatch<SetStateAction<number>>;
  predictStartTokens: number;
  setPredictStartTokens: Dispatch<SetStateAction<number>>;
  lastError: string | undefined;
  setLastError: Dispatch<SetStateAction<string | undefined>>;
  savedScrollTop: number;
  setSavedScrollTop: Dispatch<SetStateAction<number>>;
  modalState: Record<string, boolean>;
  setModalState: Dispatch<SetStateAction<Record<string, boolean>>>;
  contextMenuState: { visible: boolean; x: number; y: number };
  setContextMenuState: Dispatch<{ visible: boolean; x: number; y: number }>;
  instructModalState: Record<string, any>;
  setInstructModalState: Dispatch<SetStateAction<Record<string, any>>>;
  hordeQueuePos: number | undefined;
  setHordeQueuePos: Dispatch<number | undefined>;
  hordeProcessing: boolean;
  setHordeProcessing: Dispatch<SetStateAction<boolean>>;
  promptPreviewChunks: PromptChunk[];
  setPromptPreviewChunks: Dispatch<SetStateAction<PromptChunk[]>>;
  promptPreviewReroll: number;
  setPromptPreviewReroll: Dispatch<SetStateAction<number>>;
  ttsAvailable: boolean;
  setTTSAvailable: Dispatch<SetStateAction<boolean>>;
  triggerPredict: boolean;
  setTriggerPredict: Dispatch<SetStateAction<boolean>>;
  restartedPredict: boolean;
  setRestartedPredict: Dispatch<SetStateAction<boolean>>;
  toggleModal: (modalKey: string) => void;
  closeModal: (modalKey: string) => void;
}

interface TemplateListItem {
  name: string;
  nameNew: string;
  value: string;
  nameBack: string;
  affixes: InstructTemplate;
}
