import type { Dispatch, RefObject, SetStateAction } from 'react';

interface PromptChunk {
  type?: 'user';
  content: string;
  prob?: number;
  completion_probabilities?: CompletionProb[];
  top_logprobs?: any;
}

interface SettingsState {
  sessionStorage: SessionStorage;
  templateStorage: TemplateStorage;
  themeStorage: ThemeStorage;
  connectionStorage: ConnectionStorage;
  useSessionState: <T>(name: string, initialState: T) => [T, Dispatch<T>];
  useDBTemplates: <T>(initialState: T) => [Record<string, InstructTemplate>, Dispatch<Record<string, InstructTemplate>>];
  useDBThemes: <T>(initialState: T) => [Record<string, ThemeData>, Dispatch<Record<string, ThemeData>>];
  useDBConnections: <T>(initialState: T) => [Record<string, ConnectionData>, Dispatch<Record<string, ConnectionData>>];
  isMiyapadEndpoint: boolean;
  connections: Record<string, ConnectionData>;
  setConnections: Dispatch<Record<string, ConnectionData>>;
  selectedConnectionId: string;
  setSelectedConnectionId: Dispatch<string>;
  templates: Record<string, InstructTemplate>;
  setTemplates: Dispatch<Record<string, InstructTemplate>>;
  templateReplacements: boolean;
  setTemplateReplacements: Dispatch<boolean>;
  templatesImport: boolean;
  setTemplatesImport: Dispatch<boolean>;
  selectedTemplate: string;
  setSelectedTemplate: Dispatch<string>;
  templateList: TemplateListItem[];
  setTemplateList: Dispatch<TemplateListItem[]>;
  chatMode: boolean;
  setChatMode: Dispatch<boolean>;
  fontSizeMultiplier: number;
  setFontSizeMultiplier: Dispatch<number>;
  spellCheck: boolean;
  setSpellCheck: Dispatch<boolean>;
  attachSidebar: boolean;
  setAttachSidebar: Dispatch<boolean>;
  showProbsMode: number;
  setShowProbsMode: Dispatch<number>;
  editorFont: string;
  setEditorFont: Dispatch<string>;
  uiFont: string;
  setUIFont: Dispatch<string>;
  tokenHighlightMode: number;
  setTokenHighlightMode: Dispatch<number>;
  tokenColorMode: number;
  setTokenColorMode: Dispatch<number>;
  preserveCursorPosition: boolean;
  setPreserveCursorPosition: Dispatch<boolean>;
  promptAreaWidth: string | undefined;
  setPromptAreaWidth: Dispatch<string | undefined>;
  showAPIKey: boolean;
  setShowAPIKey: Dispatch<boolean>;
  endpoint: string;
  setEndpoint: Dispatch<string>;
  endpointAPI: number;
  setEndpointAPI: Dispatch<number>;
  endpointAPIKey: string;
  setEndpointAPIKey: Dispatch<string>;
  endpointModel: string;
  setEndpointModel: Dispatch<string>;
  seed: number;
  setSeed: Dispatch<number>;
  maxPredictTokens: number;
  setMaxPredictTokens: Dispatch<number>;
  temperature: number;
  setTemperature: Dispatch<number>;
  dynaTempRange: number;
  setDynaTempRange: Dispatch<number>;
  dynaTempExp: number;
  setDynaTempExp: Dispatch<number>;
  repeatPenalty: number;
  setRepeatPenalty: Dispatch<number>;
  repeatLastN: number;
  setRepeatLastN: Dispatch<number>;
  penalizeNl: boolean;
  setPenalizeNl: Dispatch<boolean>;
  presencePenalty: number;
  setPresencePenalty: Dispatch<number>;
  frequencyPenalty: number;
  setFrequencyPenalty: Dispatch<number>;
  topK: number;
  setTopK: Dispatch<number>;
  topP: number;
  setTopP: Dispatch<number>;
  typicalP: number;
  setTypicalP: Dispatch<number>;
  minP: number;
  setMinP: Dispatch<number>;
  tfsZ: number;
  setTfsZ: Dispatch<number>;
  mirostat: number;
  setMirostat: Dispatch<number>;
  mirostatTau: number;
  setMirostatTau: Dispatch<number>;
  mirostatEta: number;
  setMirostatEta: Dispatch<number>;
  xtcThreshold: number;
  setXtcThreshold: Dispatch<number>;
  xtcProbability: number;
  setXtcProbability: Dispatch<number>;
  dryMultiplier: number;
  setDryMultiplier: Dispatch<number>;
  dryBase: number;
  setDryBase: Dispatch<number>;
  dryAllowedLength: number;
  setDryAllowedLength: Dispatch<number>;
  dryPenaltyRange: number;
  setDryPenaltyRange: Dispatch<number>;
  drySequenceBreakers: string;
  setDrySequenceBreakers: Dispatch<string>;
  drySequenceBreakersError: string | undefined;
  setDrySequenceBreakersError: Dispatch<string | undefined>;
  bannedTokens: string;
  setBannedTokens: Dispatch<string>;
  bannedTokensError: string | undefined;
  setBannedTokensError: Dispatch<string | undefined>;
  ignoreEos: boolean;
  setIgnoreEos: Dispatch<boolean>;
  openaiPresets: boolean;
  setOpenaiPresets: Dispatch<boolean>;
  stoppingStrings: string;
  setStoppingStrings: Dispatch<string>;
  stoppingStringsError: string | undefined;
  setStoppingStringsError: Dispatch<string | undefined>;
  useBasicStoppingMode: boolean;
  setUseBasicStoppingMode: Dispatch<boolean>;
  basicStoppingModeType: string;
  setBasicStoppingModeType: Dispatch<string>;
  logitBias: LogitBiasState;
  setLogitBias: Dispatch<LogitBiasState>;
  logitBiasParam: Record<string, any>;
  setLogitBiasParam: Dispatch<Record<string, any>>;
  contextLength: number;
  setContextLength: Dispatch<number>;
  memoryTokens: MemoryTokensData;
  setMemoryTokens: Dispatch<MemoryTokensData>;
  authorNoteTokens: AuthorNoteData;
  setAuthorNoteTokens: Dispatch<AuthorNoteData>;
  authorNoteDepth: number;
  setAuthorNoteDepth: Dispatch<number>;
  worldInfo: WorldInfoData;
  setWorldInfo: Dispatch<WorldInfoData>;
  sillyTarvernWorldInfoJSON: any;
  setSillyTarvernWorldInfoJSON: Dispatch<any>;
  enabledSamplers: string[];
  setEnabledSamplers: Dispatch<string[]>;
  grammar: string;
  setGrammar: Dispatch<string>;
  useChatAPI: boolean;
  setUseChatAPI: Dispatch<boolean>;
  useTokenStreaming: boolean;
  setUseTokenStreaming: Dispatch<boolean>;
  disableLogprobs: boolean;
  setDisableLogprobs: Dispatch<boolean>;
  postSamplingProbs: boolean;
  setPostSamplingProbs: Dispatch<boolean>;
  showPromptPreview: boolean;
  setShowPromptPreview: Dispatch<boolean>;
  promptPreviewTokens: number;
  setPromptPreviewTokens: Dispatch<number>;
  currentThemeName: string;
  setCurrentThemeName: Dispatch<string>;
  allThemes: Record<string, ThemeData>;
  setAllThemes: Dispatch<Record<string, ThemeData>>;
  showMarkdownPreview: boolean;
  setShowMarkdownPreview: Dispatch<boolean>;
  ttsEnabled: boolean;
  setTTSEnabled: Dispatch<boolean>;
  ttsVoiceId: number;
  setTTSVoiceId: Dispatch<number>;
  ttsPitch: number;
  setTTSPitch: Dispatch<number>;
  ttsRate: number;
  setTTSRate: Dispatch<number>;
  ttsVolume: number;
  setTTSVolume: Dispatch<number>;
  ttsSpeakInputs: boolean;
  setTTSSpeakInputs: Dispatch<boolean>;
  ttsMaxUserInput: number;
  setTTSMaxUserInput: Dispatch<number>;
  useServerTokenization: boolean;
  setUseServerTokenization: Dispatch<boolean>;
  tokenizerModel: string | null;
  setTokenizerModel: Dispatch<string | null>;
  screenshotIncludeSessionName: boolean;
  setScreenshotIncludeSessionName: Dispatch<boolean>;
  screenshotIncludeDate: boolean;
  setScreenshotIncludeDate: Dispatch<boolean>;
  screenshotBackgroundUrl: string;
  setScreenshotBackgroundUrl: Dispatch<string>;
  screenshotBackgroundColor: string;
  setScreenshotBackgroundColor: Dispatch<string>;
  screenshotStoryFont: string;
  setScreenshotStoryFont: Dispatch<string>;
  screenshotGeneralFont: string;
  setScreenshotGeneralFont: Dispatch<string>;
  screenshotFontWeight: string;
  setScreenshotFontWeight: Dispatch<string>;
  screenshotFontSize: number;
  setScreenshotFontSize: Dispatch<number>;
  screenshotLineHeight: number;
  setScreenshotLineHeight: Dispatch<number>;
  screenshotFontColor: string;
  setScreenshotFontColor: Dispatch<string>;
  screenshotAiTextColor: string;
  setScreenshotAiTextColor: Dispatch<string>;
  screenshotModelAvatarUrl: string;
  setScreenshotModelAvatarUrl: Dispatch<string>;
  postSamplingProbs: boolean;
}

export interface GenerationState {
  promptArea: RefObject<HTMLTextAreaElement | null>;
  promptOverlay: RefObject<HTMLDivElement | null>;
  undoStack: RefObject<number[]>;
  redoStack: RefObject<any[][]>;
  probsDelayTimer: RefObject<any>;
  keyState: RefObject<any>;
  sessionReconnectTimer: RefObject<number | undefined>;
  useScrollSmoothing: RefObject<boolean>;
  hordeTaskId: RefObject<string | undefined>;
  promptPreviewElement: RefObject<HTMLSpanElement | null>;
  markdownPreviewRef: RefObject<HTMLDivElement | null>;
  isSyncingScroll: RefObject<boolean>;
  ttsNewText: RefObject<string>;
  ttsLastChunk: RefObject<string>;
  ttsQueue: RefObject<string[]>;
  ttsVoices: RefObject<SpeechSynthesisVoice[]>;
  ttsPaused: RefObject<boolean>;
  activeGenId: RefObject<number>;
  abortControllerRef: RefObject<AbortController | null>;
  promptChunks: PromptChunk[];
  setPromptChunks: Dispatch<SetStateAction<PromptChunk[]>>;
  currentPromptChunk: { index: number; top: number; left: number } | undefined;
  setCurrentPromptChunk: Dispatch<{ index: number; top: number; left: number } | undefined>;
  undoHovered: boolean;
  setUndoHovered: Dispatch<boolean>;
  showProbs: boolean;
  setShowProbs: Dispatch<boolean>;
  cancel: (() => void) | null;
  setCancel: Dispatch<SetStateAction<(() => void) | null>>;
  sessionEndpointConnecting: boolean;
  setSessionEndpointConnecting: Dispatch<boolean>;
  sessionEndpointError: string | undefined;
  setSessionEndpointError: Dispatch<string | undefined>;
  rejectedAPIKey: boolean;
  setRejectedAPIKey: Dispatch<boolean>;
  openaiModels: any[];
  setOpenaiModels: Dispatch<any[]>;
  tokens: number;
  setTokens: Dispatch<SetStateAction<number>>;
  tokensPerSec: number;
  setTokensPerSec: Dispatch<number>;
  predictStartTokens: number;
  setPredictStartTokens: Dispatch<number>;
  lastError: string | undefined;
  setLastError: Dispatch<string | undefined>;
  savedScrollTop: number;
  setSavedScrollTop: Dispatch<number>;
  modalState: Record<string, boolean>;
  setModalState: Dispatch<Record<string, boolean>>;
  contextMenuState: { visible: boolean; x: number; y: number };
  setContextMenuState: Dispatch<{ visible: boolean; x: number; y: number }>;
  instructModalState: Record<string, any>;
  setInstructModalState: Dispatch<Record<string, any>>;
  hordeQueuePos: number | undefined;
  setHordeQueuePos: Dispatch<number | undefined>;
  hordeProcessing: boolean;
  setHordeProcessing: Dispatch<boolean>;
  promptPreviewChunks: PromptChunk[];
  setPromptPreviewChunks: Dispatch<SetStateAction<PromptChunk[]>>;
  promptPreviewReroll: number;
  setPromptPreviewReroll: Dispatch<SetStateAction<number>>;
  ttsAvailable: boolean;
  setTTSAvailable: Dispatch<boolean>;
  triggerPredict: boolean;
  setTriggerPredict: Dispatch<boolean>;
  restartedPredict: boolean;
  setRestartedPredict: Dispatch<boolean>;
  toggleModal: (modalKey: string) => void;
  closeModal: (modalKey: string) => void;
}

interface TemplateListItem {
  name: string;
  nameNew: string;
  value: string;
  nameBack: string;
  affixes: InstructTemplate;
}
