interface DefaultPresets {
  endpoint: string;
  endpointAPI: number;
  endpointAPIKey: string;
  endpointModel: string;
  prompt: PromptChunk[];
  seed: number;
  maxPredictTokens: number;
  temperature: number;
  dynaTempRange: number;
  dynaTempExp: number;
  repeatPenalty: number;
  repeatLastN: number;
  penalizeNl: boolean;
  presencePenalty: number;
  frequencyPenalty: number;
  topK: number;
  topP: number;
  typicalP: number;
  minP: number;
  tfsZ: number;
  mirostat: number;
  mirostatTau: number;
  mirostatEta: number;
  xtcThreshold: number;
  xtcProbability: number;
  dryMultiplier: number;
  dryBase: number;
  dryAllowedLength: number;
  dryPenaltyRange: number;
  drySequenceBreakers: string;
  bannedTokens: string;
  stoppingStrings: string;
  useBasicStoppingMode: boolean;
  basicStoppingModeType: string;
  ignoreEos: boolean;
  openaiPresets: boolean;
  contextLength: number;
  tokenRatio: number;
  memoryTokens: MemoryTokensData;
  authorNoteTokens: AuthorNoteData;
  authorNoteDepth: number;
  worldInfo: WorldInfoData;
  logitBias: LogitBiasState;
  instructTemplates: Record<string, InstructTemplate>;
  scrollTop: number;
  enabledSamplers: string[];
  grammar: string;
  useServerTokenization: boolean;
  tokenizerModel: string | null;
  chatAPI: boolean;
  tokenStreaming: boolean;
  disableLogprobs: boolean;
  promptPreview: boolean;
  promptPreviewTokens: number;
  [key: string]: any;
}
